"""empty message

Revision ID: 14a456d1c18
Revises: 197fcd7eab9
Create Date: 2018-02-27 12:22:53.123498

"""

# revision identifiers, used by Alembic.
revision = '14a456d1c18'
down_revision = '197fcd7eab9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
