"""empty message

Revision ID: 205dbe8c074
Revises: 4524e12e81
Create Date: 2017-11-23 15:00:28.368266

"""

# revision identifiers, used by Alembic.
revision = '205dbe8c074'
down_revision = '4524e12e81'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
