"""empty message

Revision ID: 2159883ac90
Revises: 2d1d6426e91
Create Date: 2017-11-24 14:28:36.207246

"""

# revision identifiers, used by Alembic.
revision = '2159883ac90'
down_revision = '2d1d6426e91'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
