"""empty message

Revision ID: 326de2ecf2
Revises: 205dbe8c074
Create Date: 2017-11-24 13:51:30.561716

"""

# revision identifiers, used by Alembic.
revision = '326de2ecf2'
down_revision = '205dbe8c074'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manager',
    sa.Column('auth_user_id', sa.Integer(), nullable=False),
    sa.Column('club_club_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['auth_user_id'], ['auth_user.id'], ),
    sa.ForeignKeyConstraint(['club_club_id'], ['club_club.id'], ),
    sa.PrimaryKeyConstraint('auth_user_id', 'club_club_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manager')
    ### end Alembic commands ###
