"""empty message

Revision ID: 3602050e50a
Revises: 44bdbce4673
Create Date: 2017-11-30 22:20:22.405248

"""

# revision identifiers, used by Alembic.
revision = '3602050e50a'
down_revision = '44bdbce4673'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
