"""empty message

Revision ID: 4524e12e81
Revises: 4a2390e49cc
Create Date: 2017-11-23 14:59:26.846697

"""

# revision identifiers, used by Alembic.
revision = '4524e12e81'
down_revision = '4a2390e49cc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_perm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('code', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('club_club',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('introduce_one_line', sa.String(length=512), nullable=True),
    sa.Column('introduce_all', sa.Text(), nullable=True),
    sa.Column('is_show', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pages_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('title')
    )
    op.create_table('auth_perm_assoc',
    sa.Column('auth_user_id', sa.Integer(), nullable=True),
    sa.Column('auth_perm_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['auth_perm_id'], ['auth_perm.id'], ),
    sa.ForeignKeyConstraint(['auth_user_id'], ['auth_user.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_perm_assoc')
    op.drop_table('pages_page')
    op.drop_table('club_club')
    op.drop_table('auth_user')
    op.drop_table('auth_perm')
    ### end Alembic commands ###
