"""empty message

Revision ID: 461efb886fa
Revises: e5ba19efe8
Create Date: 2018-02-13 15:28:16.608094

"""

# revision identifiers, used by Alembic.
revision = '461efb886fa'
down_revision = 'e5ba19efe8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club_club', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('club_club', sa.Column('modified', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('club_club', 'modified')
    op.drop_column('club_club', 'created')
    ### end Alembic commands ###
