"""empty message

Revision ID: 4fa54386645
Revises: 3602050e50a
Create Date: 2017-11-30 23:09:37.016412

"""

# revision identifiers, used by Alembic.
revision = '4fa54386645'
down_revision = '3602050e50a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('contents', sa.Text(), nullable=False),
    sa.Column('is_shown', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('base')
    ### end Alembic commands ###
