"""empty message

Revision ID: e6a6f605b7
Revises: 4fa54386645
Create Date: 2017-11-30 23:11:52.915363

"""

# revision identifiers, used by Alembic.
revision = 'e6a6f605b7'
down_revision = '4fa54386645'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notice_notice',
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('contents', sa.Text(), nullable=False),
    sa.Column('is_shown', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('base')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.Column('modified', sa.DATETIME(), nullable=True),
    sa.Column('title', sa.VARCHAR(length=256), nullable=False),
    sa.Column('contents', sa.TEXT(), nullable=False),
    sa.Column('is_shown', sa.BOOLEAN(), nullable=False),
    sa.Column('is_public', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('notice_notice')
    ### end Alembic commands ###
