"""empty message

Revision ID: feff04be79
Revises: 1cd951d27f
Create Date: 2017-11-30 23:13:23.316558

"""

# revision identifiers, used by Alembic.
revision = 'feff04be79'
down_revision = '1cd951d27f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
